# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "master" ]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
    permissions:
      contents: read
      pages: write
      id-token: write

jobs:
  test:
    # где заускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v4
      # настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # запускаем тесты
      - run: gradle clean smoke
          # скачиваем историю тестов
          #- uses: actions/checkout@v3
        #if: always()
        #continue-on-error: true
        #with:
        #ref: gh-pages
        #path: gh-pages
      # генерируем отчет
      - uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
